### ISSUE TITLE
APP_ENV doesn't work as expected

### ISSUE THREAD

**Issue by siemya** [goatandsheep/react-native-dotenv#131]
I want to be able to use `development` and `production` config files according to the APP_ENV variable I pass. 

But even if I pass the env as a variable, it uses `development` for debug and `production` for release.

```
"android": "APP_ENV=development react-native run-android --variant 'devDebug'",
"android-prod": "APP_ENV=production react-native run-android --variant 'prodDebug'",
"build-android-dev": "cd android && APP_ENV=development ./gradlew assembleDevRelease",
"build-android": "cd android && APP_ENV=production ./gradlew assembleProdRelease",
```

**Comment by goatandsheep** [comment]
I wonder if this is a caching issue. Try this for now https://www.npmjs.com/package/react-native-clean-project

**Comment by siemya** [comment]
@goatandsheep unfortunately no change

**Comment by goatandsheep** [comment]
This looks exactly like the stuff in the [multi env wiki](https://github.com/goatandsheep/react-native-dotenv/wiki/Multi-env-troubleshooting). Let me know if that helps

**Comment by siemya** [comment]
@goatandsheep 

It doesn't really help actually.

As far as I can see I can't have the flexibility as I wrote above.

**Comment by goatandsheep** [comment]
One thing I can say is that gradlew is not react native so `APP_ENV` has no power there. Neither does this library. You'll have to rebuild

**Comment by goatandsheep** [comment]
btw, you shouldn't need `APP_ENV` for `production` and `development` as those are built in. You're better off controlling it through the variants inside your gradlew

**Comment by f4z3k4s** [comment]
The problem I ran into using `APP_ENV`:

As I understand `APP_ENV` should be provided to the packager, not the `run-android` command. So if I run `APP_ENV=staging npx react-native start` it uses `.env.staging` as a result. 

That is all good if you have the ability to spawn a custom packager, e.g.: in debug builds. But what happens when you run a release build? If `bundleInStaging` in `app/build.gradle` is set to `true`, it will spawn a custom packager during the build process, regardless if you have a packager running with the proper `APP_ENV` set. And in the custom packager's environment, `APP_ENV` will be unset. If you set `bundleInStaging` to false and you try to build your own bundle with `APP_ENV=staging npx react-native bundle ...` it still spawns it's own packager, and the env you specified for the bundle command doesn't apply for the packager. So all in all, APP_ENV is unusable for release builds according to my understanding.

Am I missing something or do you experience the same?

**Comment by samuelpetroline** [comment]
I'm having the same problem. When I try to build a release version with `APP_ENV=staging` the content is ignored and it always get the `.env.production` content

**Comment by goatandsheep** [comment]
I figured out the issue while doing some experimentation, but I'm going to write some documentation on it this weekend

**Comment by caiangums** [comment]
Hey! 👋 

I noticed that you are passing the `APP_ENV` variable at the `react-native run-android` command when it should be passed at the starting of the metro server(`react-native start`). It is possible to see that [in this section of the README.md](https://github.com/goatandsheep/react-native-dotenv#experimental-feature).

I suggest changing your `scripts` section in your `package.json` to something like:

```json
{
  "scripts": {
    "start": "APP_ENV=development react-native start --reset-cache",
    "start-prod": "APP_ENV=production react-native start --reset-cache"
  }
} 
```

It is important to note that your `.env` files should respect the pattern `.env.<environment>`. So, I also suggest changing your main/production `.env` file to `.env.main` or `.env.production`, so you could pass them as `APP_ENV=main` or `APP_ENV=production` 😄 

Hope that helps!

**Comment by f4z3k4s** [comment]
@caiangums Thanks for the motivation to help. I think all of us read the documentation, and we all provided the `APP_ENV` variable to the `react-native start` command. That's essentially the source of the problem. Please re-read my above comment and check how release versions are built. Release versions on Android spawn their own packager if `bundleInYourCustomName` is set to `true` in `app/build.gradle`. Therefore, because it internally spawns it's own packager, you are unable to provide any env variables, like `APP_ENV` dynamically from scripts. 

I ended up using [react-native-config](https://github.com/luggit/react-native-config) because of the following reasons:

-  I've had no caching issues with that package (which drove me crazy with this)
- I can use the environment variables from native code as well, and I only have one `.env` file as configuration
- It provides `APP_ENV` alternative to `react-native run-android` command and not the `react-native start` command, hence the issue I described above is non-existent.

Anyway, thanks @goatandsheep for your work and your kindly responses, I just found that the other package better suits my needs.

**Comment by caiangums** [comment]
@f4z3k4s Thanks for the clarification! I used `react-native-config` before but the approach from this library seems easier to configure 🙏 

While trying to change some code at `metro.config.js` to properly pass the actual values, no success was accomplished from my side. Hope that @goatandsheep could give a better solution 😅

**Comment by goatandsheep** [comment]
I need to figure out how the other library deals with caching issues

**Comment by hoangnguyen8895** [comment]
I have same issue, hope to receive a solution from you soon @goatandsheep :D

**Comment by goatandsheep** [comment]
If you're using `APP_ENV`, you should not use `development` nor `production` as values nor should you have a `.env.development` nor `.env.production`. This is a Babel and Node thing that I have little control over unfortunately and is consistent with many other platforms that have an override option, like [Gatsby](https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#additional-environments-staging-test-etc).

This has been added to the README.

**Comment by Asranov** [comment]
Hey , i'm also experiencing the same issue. Has anyone found a solution for this problem?

**Comment by caiangums** [comment]
Hi @Asranov! Turns out that I changed my approach to other libs for solving this issue.

If you want, you can try the approach mentioned by @f4z3k4s using [react-native-config](https://github.com/luggit/react-native-config).
