### ISSUE TITLE
Relation to zetachang/react-native-dotenv - migration guide?

### ISSUE THREAD

**Issue by actuallymentor** [goatandsheep/react-native-dotenv#18]
For a longer-time `react-native-dotenv` user it is very confusing to suddenly have a different repo and no `breaking changes` or `migration` mentions in the readme.

Is this the same/related package? Why was this moved?

**Comment by andreslargo** [comment]
+1

**Comment by teamzz111** [comment]
+1 

I've the same problem, is related? Other repository has been closed

**Comment by goatandsheep** [comment]
That's very fair! There were a number of security issues with the other repository. It hadn't been updated for years. The owner was unable to maintain it. I reached out to him and he transferred ownership to me so that I can maintain it. Migration guide is _very_ good feedback. I'm going to work on something of the sort sometime this week.

I took babel-plugin-dotenv-import as the starting point as it was also derived from @zetachang 's package but solved a number of pending issues and requested pull requests from various contributors. We decided that it was best to start over if we wanted to make sure to improve quality. There are a number of more fixes and features on the way.

What do you think? Good idea? I'm open to ideas and improvements.

**Comment by actuallymentor** [comment]
> What do you think? Good idea? I'm open to ideas and improvements.

First off: I have nothing but respect for fellow open source contributors, thank you for picking up an abandoned project.

My main feedback points would be:

1. Your current setup is not backwards compatible so a migration guide seems like a first priority
2. As me and @teamzz111 indicated, the above info would help ease the confusion of long-time users, maybe a little 'reason for this migration' section

**Comment by goatandsheep** [comment]
I've created the [beginning of a migration guide](https://github.com/goatandsheep/react-native-dotenv/wiki/Migration-Guide)

**Comment by actuallymentor** [comment]
> I've created the beginning of a migration guide

I see you added the history and migration guide to the `README.md`, thank you for picking up this issue so quickly. In it's current form I think most people will be able to understand the history and have a clear path to migrating.

One thing that might be worth it is using some more conventional documentation terminology, for example changing:

> For those moving from v0.2.0 to the latest version, you will find it is quite the jump.

To something like:

**Breaking changes:** moving from `v0.x` to `v2.x` changes both the setup and usage of this package. Please see the [Migration guide](https://github.com/goatandsheep/react-native-dotenv/wiki/Migration-Guide).

**Comment by goatandsheep** [comment]
@actuallymentor I've since made those changes. Can we close this ticket?

**Comment by actuallymentor** [comment]
Yup, thanks again for the quick communication!
