### ISSUE TITLE
Doesn't set process.env

### ISSUE THREAD

**Issue by wholebuzz** [goatandsheep/react-native-dotenv#187]
This project is misleadingly named.  Consider renaming to `react-native-configfile`.

"dotenv" is specifically named for [Environment Variables](https://en.wikipedia.org/wiki/Environment_variable) accessed through `process.env`.

I need to access the variables from `.env` and `.env.local` through `process.env`, in order to share code between React and React Native.

**Comment by goatandsheep** [comment]
Hi @wholebuzz I appreciate your opinion, but this library lists dotenv as a dependency and it operates using dotenv files so the name is staying!

However, I like your idea. I think it is possible to replace instances of process.env with the value object, since this is a babel plugin. I'm doing some refactoring and documentation updates this upcoming week so any help on this is appreciated and I will take seriously.

**Comment by goatandsheep** [comment]
So I found something similar but it doesn't use dotenv-flow: https://github.com/jordansexton/babel-plugin-transform-inline-environment-variables

Let me know if this is what you're thinking about? I did a few experiments copying the code from that library and it worked quite well

**Comment by goatandsheep** [comment]
@wholebuzz I did some initial work on a branch https://github.com/goatandsheep/react-native-dotenv/tree/bugfix/gh-187 if you're interested in helping out with adding the options let me know!
