### ISSUE TITLE
Importing variables throws an error in TypeScript.

### ISSUE THREAD

**Issue by dmahajan980** [goatandsheep/react-native-dotenv#269]
- [ ] Asked question in discussions
- [x] Tried the troubleshooting Wiki
- [x] Followed the migration Wiki

**Describe the bug**
Whenever an environment variable is imported from the module, TypeScript throws the following error:

<img width="486" alt="Screenshot 2021-12-20 at 7 27 54 PM" src="https://user-images.githubusercontent.com/37256767/146779129-d3cf7cd6-3f02-4a78-83ea-fb9458f4e2f9.png">

**To Reproduce**
1. Create an environment variable in `.env` file.
2. Import the same variable from the module `react-native-dotenv` in TypeScript file.

**Expected behavior**
TypeScript should not throw any errors/warnings if the variable exists.

**Screenshots**
My Babel Config is as follows:

<img width="501" alt="Screenshot 2021-12-20 at 7 36 37 PM" src="https://user-images.githubusercontent.com/37256767/146779567-9045f100-d28f-415c-aabe-102939c7aa00.png">

Env file:

<img width="154" alt="Screenshot 2021-12-20 at 7 42 02 PM" src="https://user-images.githubusercontent.com/37256767/146780293-1cd48681-677f-41f4-91b7-01728fd7955d.png">

**Version Details**
React Native Dotenv: ^3.3.1
React Native: 0.66.4
TypeScript: ^4.4.4
React: 17.0.2

**Additional context**
The variables seem to hold values when used in development builds. However, TypeScript should not throw any errors if user has followed all the steps in the documentation.

**Comment by fristyr** [comment]
I have the same issue

**Comment by goatandsheep** [comment]
Have you tried the `@types` package? Does it help?

**Comment by fristyr** [comment]
Yep. "@types/react-native-dotenv": "^0.2.0",

**Comment by dmahajan980** [comment]
> Yep. "@types/react-native-dotenv": "^0.2.0",

Yes, this is what I've been using in my project.

**Comment by ineshbose** [comment]
Same issue here!

**Comment by goatandsheep** [comment]
HM... I'm not sure what to do to fix this 😔

**Comment by cscovino** [comment]
I used it in this way and it works

```
import axios from 'axios';
import dotenv from 'react-native-dotenv';

const API = axios.create({
  baseURL: dotenv.API_BASE_URL,
});
```

I think this is because the type definition is exporting a const

```
// Type definitions for react-native-dotenv 0.2
// Project: https://github.com/zetachang/react-native-dotenv
// Definitions by: hmajid2301 <https://github.com/hmajid2301>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 3.0

interface Env {
    [name: string]: string;
}

declare const env: Env;
export = env;
```

**Comment by cscovino** [comment]
According with the type [definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/react-native-dotenv/index.d.ts), we should import env as default like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/react-native-dotenv/react-native-dotenv-tests.ts):

```
import env from "react-native-dotenv";

env.API_KEY;
```

This eliminates the error, but later I have this error `Default import is not supported`

**Comment by goatandsheep** [comment]
Yup the default import is purposely disabled because the values are replaced by babel in compile

**Comment by cscovino** [comment]
Ok. My workaround was to create a file named `env.d.ts`

```
declare module 'react-native-dotenv' {
  export const API_URL: string;
}
```

**Comment by goatandsheep** [comment]
I feel like the definitely typed package is probably a time waster and shouldn't be recommended. I tried to think about how it could be fixed but you kinda just need to declare the module types yourself in the end

**Comment by cscovino** [comment]
Yes. I think the only way it's to define types by yourself 🙃

**Comment by goatandsheep** [comment]
since this is in the README, I will close this ticket. feel free to reopen if this doesn't work

**Comment by vjau** [comment]
> since this is in the README, I will close this ticket. feel free to reopen if this doesn't work

The README recommends two ways to get typescript to work, way 1 "easy mode", and way 2.
Way 2 is just to define the types yourself.
Way 1 "easy mode" doesn't work.

**Comment by goatandsheep** [comment]
I'm sorry way 2 hasn't worked for you but for some it has worked very well. How can I help?

**Comment by vjau** [comment]
> I'm sorry way 2 hasn't worked for you but for some it has worked very well. How can I help?

I wrote way 1
It's way 1 that is not working. It should probably be removed from the README.

**Comment by goatandsheep** [comment]
Sorry that's my bad for not reading properly, but the way this works is that if something goes wrong, you can suggest that maybe the method doesn't work at all or you can ask what you did wrong. This is a community where we have to keep our minds open to the possibility that we made a mistake somewhere and that it's ok because we can learn together. I'm happy to take a look at your code to see why things are not working. Maybe it's an edge case on the library? Maybe I can update the readme to account to your edge case. I can't just remove suggestions because you've stated it didn't work for you.

**Comment by vjau** [comment]
Ok, last try.

The README is recommending two ways to get typescript to work with this package.
OPTION 2 is just to `declare` your env variables by hand.
OPTION 1, presented as the _easy way_, require to install the definitely typed type package.

However,  as explained by the thread starter, and multiple participants in this thread, this way doesn't work.

Actually, you agree yourself that it doesn't work since you wrote `I feel like the definitely typed package is probably a time waster and shouldn't be recommended. I tried to think about how it could be fixed but you kinda just need to declare the module types yourself in the end`

So you agree that OPTION1 is not working and **shouldn't be recommended**

Hence, the README is wrong.

Thank you.

**Comment by duncan-iaria** [comment]
Can confirm, Option 1 does not work for me.

**Comment by goatandsheep** [comment]
If you want to open a pull request I'll accept it

**Comment by stevehanson** [comment]
I also ran into this issue, where the easy option did not work. Just opened PR #360 to update the readme.

**Comment by goatandsheep** [comment]
**merged**
