### ISSUE TITLE
Android release build is picking debug environment instead of prod

### ISSUE THREAD

**Issue by Sterlingryan** [goatandsheep/react-native-dotenv#56]
I'm having an issue where the Android release build is picking up the variables inside .env instead of variables inside .env.production. iOS works fine.

"react-native": "0.62.2",
"react-native-dotenv": "^2.3.0",
"babel-plugin-dotenv-import": "^2.1.0",

.bablerc:
```
{
    "plugins": [
        "add-react-displayname",
        "./node_modules/@heap/react-native-heap/instrumentor/src/index.js",
        ["dotenv-import", {
            "moduleName": "@env",
            "path": ".env",
            "blacklist": null,
            "whitelist": null,
            "safe": false,
            "allowUndefined": true
        }],
    ]
}
```
babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
```

**Comment by goatandsheep** [comment]
You can either wait for #1 or set path to `.env.production`

**Comment by goatandsheep** [comment]
you may also use the env option in [babel](https://babeljs.io/docs/en/options#env)

**Comment by FanchenBao** [comment]
I am having the same issue. Running `react-native run-android --variant release` does not pick up `.env.production`. It still loads `.env`. I am able to work around this problem by changing the path to `.env.production`, but that doesn't feel like a robust fix.

The same issue cannot be repeated in iOS, because for whatever reason, I need to manually bundle in iOS. And the `react-native bundle` commands is picking up `.env.production` if `NODE_ENV=production` is specified. However, specifying `NODE_ENV=production` does not help building release version for android.

**Comment by goatandsheep** [comment]
Some people are saying to follow the Android signing guide https://reactnative.dev/docs/signed-apk-android#adding-signing-config-to-your-apps-gradle-config

**Comment by FanchenBao** [comment]
Thanks for the response. I have signing set up already, but still not working. I keep getting this error message:

```
SyntaxError: /.../src/config/appConfig.js: "BACKEND_API_ENDPOINT" is not defined in .env
>  7 | import {BACKEND_API_ENDPOINT, ENV} from '@env';
   5 |  */
     |         ^^^^^^^^^^^^^^^^^^^^
```
I think it is because `.env.production` is not loaded, so the system looks in `.env` for `BACKEND_API_ENDPOINT`. But `BACKEND_API_ENDPOINT` is not defined in `.env`; it is only defined in `.env.production`.

I have also tried to define `BACKEND_API_ENDPOINT` in `.env` and give it a dummy value, hoping that the system will overwrite the dummy with the real one in `.env.production`. Unfortunately, the system picks the dummy value directly.

**Comment by goatandsheep** [comment]
Do you think you can try adding the variable to `.env` just to troubleshoot? Maybe it's not loading properly at all!
